/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.unicamp.ic.mc536.prontosocorro.doenca;
import br.unicamp.ic.mc536.prontosocorro.consulta.InsereConsulta;
import br.unicamp.ic.mc536.prontosocorro.prescricao.Prescricao;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Administrador
 */
public class GetDoenca extends javax.swing.JFrame {

    /**
     * Creates new form ConsFuncionario
     */
    
    InsereConsulta ret;
    
    public GetDoenca(InsereConsulta ins) {
        initComponents();
        this.ret = ins;
    }

    private GetDoenca() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    private void search() {
        if (chSemFiltro.isSelected()){
            atualizaTabela(Doenca.consultar("",(short)-1));
            lbErro.setText("");
        } else if(chCID.isSelected()) {
            atualizaTabela(Doenca.consultar(edCID.getText(),(short)1));
            lbErro.setText("");
        } else if(chNome.isSelected()) {
            atualizaTabela(Doenca.consultar(edNome.getText(),(short)2));
            lbErro.setText("");
        }
    }
    
    protected void atualizaTabela(ResultSet rs){
        DefaultTableModel modelotabela = (DefaultTableModel) tabela.getModel();
        modelotabela.setColumnCount(2);
        modelotabela.setRowCount(0);
        tabela.getColumnModel().getColumn(0).setWidth(20);
        tabela.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        tabela.getColumnModel().getColumn(0).setHeaderValue("CID");
        tabela.getColumnModel().getColumn(1).setHeaderValue("Nome");
        
        int linha = 0;
        try{
            if(rs != null) {  
                while(rs.next()){
                      modelotabela.addRow(new String[modelotabela.getColumnCount()]);
                      modelotabela.setValueAt(rs.getString("cid"), linha, 0);
                      modelotabela.setValueAt(rs.getString("nome"), linha, 1);
                      linha++;
                  }
            }
        }catch(SQLException e){
            System.err.println("Erro: " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        edCID = new javax.swing.JTextField();
        edNome = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        chSemFiltro = new javax.swing.JCheckBox();
        chNome = new javax.swing.JCheckBox();
        chCID = new javax.swing.JCheckBox();
        btLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        lbErro = new javax.swing.JLabel();
        btVoltar = new javax.swing.JButton();
        btSelecionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Busca de Médicos");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel5.setName(""); // NOI18N
        jPanel5.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Busca de Doença");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(0, 20, 570, 30);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Filtros de busca:");
        jPanel6.add(jLabel6);
        jLabel6.setBounds(40, 10, 140, 20);

        edCID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edCID.setEnabled(false);
        jPanel6.add(edCID);
        edCID.setBounds(120, 40, 100, 25);

        edNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edNome.setEnabled(false);
        jPanel6.add(edNome);
        edNome.setBounds(120, 70, 280, 25);

        btBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btBuscar.setText("BUSCAR");
        btBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btBuscarMouseClicked(evt);
            }
        });
        jPanel6.add(btBuscar);
        btBuscar.setBounds(420, 60, 100, 50);

        buttonGroup1.add(chSemFiltro);
        chSemFiltro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chSemFiltro.setSelected(true);
        chSemFiltro.setText("Sem Filtro");
        jPanel6.add(chSemFiltro);
        chSemFiltro.setBounds(315, 40, 97, 30);

        buttonGroup1.add(chNome);
        chNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chNome.setText("Nome");
        chNome.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chNomeItemStateChanged(evt);
            }
        });
        jPanel6.add(chNome);
        chNome.setBounds(10, 70, 70, 24);

        buttonGroup1.add(chCID);
        chCID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chCID.setText("CID");
        chCID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chCIDItemStateChanged(evt);
            }
        });
        jPanel6.add(chCID);
        chCID.setBounds(10, 40, 70, 24);

        btLimpar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.setToolTipText("");
        btLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btLimparMouseClicked(evt);
            }
        });
        jPanel6.add(btLimpar);
        btLimpar.setBounds(420, 20, 100, 30);

        jPanel5.add(jPanel6);
        jPanel6.setBounds(20, 60, 530, 120);

        tabela.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 4"
            }
        ));
        tabela.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jScrollPane1.setViewportView(tabela);

        jPanel5.add(jScrollPane1);
        jScrollPane1.setBounds(20, 190, 530, 340);

        lbErro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbErro.setForeground(new java.awt.Color(255, 0, 51));
        lbErro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbErro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel5.add(lbErro);
        lbErro.setBounds(20, 540, 400, 30);

        btVoltar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btVoltar.setText("VOLTAR");
        btVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btVoltarMouseClicked(evt);
            }
        });
        jPanel5.add(btVoltar);
        btVoltar.setBounds(450, 580, 100, 40);

        btSelecionar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSelecionar.setText("SELECIONAR");
        btSelecionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSelecionarMouseClicked(evt);
            }
        });
        jPanel5.add(btSelecionar);
        btSelecionar.setBounds(320, 580, 130, 40);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 0, 570, 630);

        setSize(new java.awt.Dimension(585, 669));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btBuscarMouseClicked
        search();
    }//GEN-LAST:event_btBuscarMouseClicked

    private void chNomeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chNomeItemStateChanged
        edNome.setEnabled(chNome.isSelected());
    }//GEN-LAST:event_chNomeItemStateChanged

    private void chCIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chCIDItemStateChanged
        edCID.setEnabled(chCID.isSelected());
    }//GEN-LAST:event_chCIDItemStateChanged
 
    private void btLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLimparMouseClicked
        edCID.setText("");
        edNome.setText("");
        chSemFiltro.setSelected(true);
        btBuscarMouseClicked(evt);
    }//GEN-LAST:event_btLimparMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        search();
    }//GEN-LAST:event_formWindowActivated

    private void btVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVoltarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btVoltarMouseClicked

    private void btSelecionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSelecionarMouseClicked
        if(tabela.getSelectedRowCount() != 0){
            String cid = tabela.getValueAt(tabela.getSelectedRow(),0).toString();
            ArrayList<String> diag = ret.getConsulta().getListaDiagnosticos();
            diag.add(cid);                    
            ret.getConsulta().setListaDiagnosticos(diag);                    
            ret.atualizaTabelaDiagnostico();            
            this.dispose();  
        } else {
            lbErro.setText("Selecione uma doença");
        }

    }//GEN-LAST:event_btSelecionarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GetDoenca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GetDoenca().setVisible(true);
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSelecionar;
    private javax.swing.JButton btVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chCID;
    private javax.swing.JCheckBox chNome;
    private javax.swing.JCheckBox chSemFiltro;
    private javax.swing.JTextField edCID;
    private javax.swing.JTextField edNome;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbErro;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
