/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.unicamp.ic.mc536.prontosocorro.exame;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Administrador
 */
public class BuscaExame extends javax.swing.JFrame {

    /**
     * Creates new form ConsFuncionario
     */
    public BuscaExame() {
        initComponents();
    }
    
    private void search() {
        if (chSemFiltro.isSelected()){
            atualizaTabela(Exame.consultar("","",null,null,(short)-1));
            lbErro.setText("");
        } else if(chID.isSelected()) {
            try {
                int id = Integer.parseInt(edID.getText());
                atualizaTabela(Exame.consultar(""+id,"",null,null,(short)1));
                lbErro.setText("");
            } catch (NumberFormatException e) {
                lbErro.setText("O código deve ser um valor numérico!");
            }
        }
        else if(chPaciente.isSelected()) {
            atualizaTabela(Exame.consultar(edPaciente.getText(),"",null,null,(short)6));
            lbErro.setText("");
        }
        else if(chMedico.isSelected()) {
            atualizaTabela(Exame.consultar(edMedico.getText(),"",null,null,(short)6));
            lbErro.setText("");
        } 
        else if(chMedicoePaciente.isSelected()) {
            atualizaTabela(Exame.consultar(edMedico.getText(),edPaciente.getText(),null,null,(short)6));
            lbErro.setText("");
        } 
        else if(chData.isSelected()) {
            atualizaTabela(Exame.consultar(edLaboratorio.getText(),"",null,null,(short)6));
            lbErro.setText("");
        }
    }
    
    protected void atualizaTabela(ResultSet rs){
        DefaultTableModel modelotabela = (DefaultTableModel) tabela.getModel();
        modelotabela.setColumnCount(4);
        modelotabela.setRowCount(0);

        tabela.getColumnModel().getColumn(0).setHeaderValue("ID");
        tabela.getColumnModel().getColumn(1).setHeaderValue("Princípio Ativo");
        tabela.getColumnModel().getColumn(2).setHeaderValue("Dosagem");
        tabela.getColumnModel().getColumn(3).setHeaderValue("Contra-Indicação");
        
        int linha = 0;
        try{
            if(rs != null) {  
                while(rs.next()){
                      modelotabela.addRow(new String[modelotabela.getColumnCount()]);
                      modelotabela.setValueAt(rs.getString("id_medicamento"), linha, 0);
                      modelotabela.setValueAt(rs.getString("principio_ativo"), linha, 1);
                      modelotabela.setValueAt(rs.getString("dosagem"), linha, 2);
                      modelotabela.setValueAt(rs.getString("contra_indicacao"), linha, 3);
                      linha++;
                  }
            }
        }catch(SQLException e){
            System.err.println("Erro: " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        edID = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        chSemFiltro = new javax.swing.JCheckBox();
        chData = new javax.swing.JCheckBox();
        chID = new javax.swing.JCheckBox();
        btLimpar = new javax.swing.JButton();
        btInserir = new javax.swing.JButton();
        chPaciente = new javax.swing.JCheckBox();
        edPaciente = new javax.swing.JTextField();
        chMedico = new javax.swing.JCheckBox();
        edLaboratorio = new javax.swing.JTextField();
        chMedicoePaciente = new javax.swing.JCheckBox();
        edMedico = new javax.swing.JTextField();
        chLaboratorio = new javax.swing.JCheckBox();
        edData = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        lbErro = new javax.swing.JLabel();
        btVoltar = new javax.swing.JButton();
        btInserir2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Busca de Exames");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel5.setName(""); // NOI18N
        jPanel5.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Busca Exame");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(0, 20, 570, 30);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Filtros de busca:");
        jPanel6.add(jLabel6);
        jLabel6.setBounds(40, 10, 140, 20);

        edID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edID.setEnabled(false);
        jPanel6.add(edID);
        edID.setBounds(130, 40, 100, 23);

        btBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btBuscar.setText("BUSCAR");
        btBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btBuscarMouseClicked(evt);
            }
        });
        jPanel6.add(btBuscar);
        btBuscar.setBounds(420, 80, 100, 50);

        buttonGroup1.add(chSemFiltro);
        chSemFiltro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chSemFiltro.setSelected(true);
        chSemFiltro.setText("Sem Filtro");
        jPanel6.add(chSemFiltro);
        chSemFiltro.setBounds(315, 40, 95, 30);

        buttonGroup1.add(chData);
        chData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chData.setText("Data");
        chData.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chDataItemStateChanged(evt);
            }
        });
        chData.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chDataStateChanged(evt);
            }
        });
        jPanel6.add(chData);
        chData.setBounds(10, 190, 100, 25);

        buttonGroup1.add(chID);
        chID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chID.setText("ID");
        chID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chIDItemStateChanged(evt);
            }
        });
        jPanel6.add(chID);
        chID.setBounds(10, 40, 70, 25);

        btLimpar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.setToolTipText("");
        btLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btLimpar.setOpaque(false);
        btLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btLimparMouseClicked(evt);
            }
        });
        jPanel6.add(btLimpar);
        btLimpar.setBounds(420, 40, 100, 30);

        btInserir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btInserir.setText("INSERIR");
        btInserir.setToolTipText("");
        btInserir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btInserirMouseClicked(evt);
            }
        });
        jPanel6.add(btInserir);
        btInserir.setBounds(-60, 520, 110, 40);

        buttonGroup1.add(chPaciente);
        chPaciente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chPaciente.setText("Paciente");
        chPaciente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chPacienteItemStateChanged(evt);
            }
        });
        chPaciente.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chPacienteStateChanged(evt);
            }
        });
        jPanel6.add(chPaciente);
        chPaciente.setBounds(10, 70, 120, 25);

        edPaciente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edPaciente.setEnabled(false);
        jPanel6.add(edPaciente);
        edPaciente.setBounds(130, 70, 260, 23);

        buttonGroup1.add(chMedico);
        chMedico.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chMedico.setText("Médico");
        chMedico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chMedicoItemStateChanged(evt);
            }
        });
        chMedico.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chMedicoStateChanged(evt);
            }
        });
        jPanel6.add(chMedico);
        chMedico.setBounds(10, 100, 90, 25);

        edLaboratorio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edLaboratorio.setEnabled(false);
        jPanel6.add(edLaboratorio);
        edLaboratorio.setBounds(130, 160, 260, 23);

        buttonGroup1.add(chMedicoePaciente);
        chMedicoePaciente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chMedicoePaciente.setText("Médico e paciente");
        chMedicoePaciente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chMedicoePacienteItemStateChanged(evt);
            }
        });
        chMedicoePaciente.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chMedicoePacienteStateChanged(evt);
            }
        });
        jPanel6.add(chMedicoePaciente);
        chMedicoePaciente.setBounds(10, 130, 140, 25);

        edMedico.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edMedico.setEnabled(false);
        jPanel6.add(edMedico);
        edMedico.setBounds(130, 100, 260, 23);

        buttonGroup1.add(chLaboratorio);
        chLaboratorio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chLaboratorio.setText("Laboratório");
        chLaboratorio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chLaboratorioItemStateChanged(evt);
            }
        });
        chLaboratorio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chLaboratorioStateChanged(evt);
            }
        });
        jPanel6.add(chLaboratorio);
        chLaboratorio.setBounds(10, 160, 100, 25);

        edData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        edData.setEnabled(false);
        jPanel6.add(edData);
        edData.setBounds(130, 190, 130, 20);

        jPanel5.add(jPanel6);
        jPanel6.setBounds(20, 60, 530, 230);

        tabela.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 4"
            }
        ));
        tabela.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jScrollPane1.setViewportView(tabela);

        jPanel5.add(jScrollPane1);
        jScrollPane1.setBounds(20, 310, 530, 220);

        lbErro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbErro.setForeground(new java.awt.Color(255, 0, 51));
        lbErro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbErro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel5.add(lbErro);
        lbErro.setBounds(20, 540, 350, 30);

        btVoltar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btVoltar.setText("VOLTAR");
        btVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btVoltarMouseClicked(evt);
            }
        });
        jPanel5.add(btVoltar);
        btVoltar.setBounds(450, 580, 100, 40);

        btInserir2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btInserir2.setText("INSERIR");
        btInserir2.setToolTipText("");
        btInserir2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btInserir2MouseClicked(evt);
            }
        });
        jPanel5.add(btInserir2);
        btInserir2.setBounds(20, 580, 110, 40);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 0, 570, 630);

        setSize(new java.awt.Dimension(585, 669));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btBuscarMouseClicked
        search();
    }//GEN-LAST:event_btBuscarMouseClicked

    private void chDataItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chDataItemStateChanged
        edLaboratorio.setEnabled(chData.isSelected());
    }//GEN-LAST:event_chDataItemStateChanged

    private void chIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chIDItemStateChanged
        edID.setEnabled(chID.isSelected());
    }//GEN-LAST:event_chIDItemStateChanged
 
    private void btLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLimparMouseClicked
        edID.setText("");
        edLaboratorio.setText("");
        chSemFiltro.setSelected(true);
        btBuscarMouseClicked(evt);
    }//GEN-LAST:event_btLimparMouseClicked

    private void btInserirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btInserirMouseClicked
        InsereExame insere = new InsereExame();
        insere.setVisible(true);
    }//GEN-LAST:event_btInserirMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        search();
    }//GEN-LAST:event_formWindowActivated

    private void btVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVoltarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btVoltarMouseClicked

    private void chPacienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chPacienteItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_chPacienteItemStateChanged

    private void chMedicoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chMedicoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_chMedicoItemStateChanged

    private void chMedicoePacienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chMedicoePacienteItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_chMedicoePacienteItemStateChanged

    private void chLaboratorioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chLaboratorioItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_chLaboratorioItemStateChanged

    private void chPacienteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chPacienteStateChanged
        edPaciente.setEnabled(chPaciente.isSelected());
    }//GEN-LAST:event_chPacienteStateChanged

    private void chMedicoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chMedicoStateChanged
        edMedico.setEnabled(chMedico.isSelected());
    }//GEN-LAST:event_chMedicoStateChanged

    private void chMedicoePacienteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chMedicoePacienteStateChanged
        edMedico.setEnabled(chMedicoePaciente.isSelected());
        edPaciente.setEnabled(chMedicoePaciente.isSelected());
    }//GEN-LAST:event_chMedicoePacienteStateChanged

    private void chLaboratorioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chLaboratorioStateChanged
        edLaboratorio.setEnabled(chLaboratorio.isSelected());
    }//GEN-LAST:event_chLaboratorioStateChanged

    private void chDataStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chDataStateChanged
        edData.setEnabled(chData.isSelected());
    }//GEN-LAST:event_chDataStateChanged

    private void btInserir2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btInserir2MouseClicked
        InsereExame insere = new InsereExame();
        insere.setVisible(true);
    }//GEN-LAST:event_btInserir2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscaExame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new BuscaExame().setVisible(true);
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btInserir;
    private javax.swing.JButton btInserir2;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chData;
    private javax.swing.JCheckBox chID;
    private javax.swing.JCheckBox chLaboratorio;
    private javax.swing.JCheckBox chMedico;
    private javax.swing.JCheckBox chMedicoePaciente;
    private javax.swing.JCheckBox chPaciente;
    private javax.swing.JCheckBox chSemFiltro;
    private javax.swing.JFormattedTextField edData;
    private javax.swing.JTextField edID;
    private javax.swing.JTextField edLaboratorio;
    private javax.swing.JTextField edMedico;
    private javax.swing.JTextField edPaciente;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbErro;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
