/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.unicamp.ic.mc536.prontosocorro.medico;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Administrador
 */
public class BuscaMedico extends javax.swing.JFrame {

    /**
     * Creates new form ConsFuncionario
     */
    public BuscaMedico() {
        initComponents();
    }
    
    private void search() {
        if (chSemFiltro.isSelected()){
            atualizaTabela(Medico.consultar("",(short)-1));
            lbErro.setText("");
        } else if(chCRM.isSelected()) {
            try {
                int crm = Integer.parseInt(edCRM.getText());
                atualizaTabela(Medico.consultar(""+crm,(short)1));
                lbErro.setText("");
            } catch (NumberFormatException e) {
                lbErro.setText("O código deve ser um valor numérico!");
            }
        } else if(chNome.isSelected()) {
            atualizaTabela(Medico.consultar(edNome.getText(),(short)2));
            lbErro.setText("");
        } else if(chEspecialidade.isSelected()) {
            atualizaTabela(Medico.consultar(edEspecialidade.getText(),(short)3));
            lbErro.setText("");
        }
    }
    
    protected void atualizaTabela(ResultSet rs){
        DefaultTableModel modelotabela = (DefaultTableModel) tabela.getModel();
        modelotabela.setColumnCount(3);
        modelotabela.setRowCount(0);

        tabela.getColumnModel().getColumn(0).setHeaderValue("CRM");
        tabela.getColumnModel().getColumn(1).setHeaderValue("Nome");
        tabela.getColumnModel().getColumn(2).setHeaderValue("Especialidade");
        int linha = 0;
        try{
            if(rs != null) {  
                while(rs.next()){
                      modelotabela.addRow(new String[modelotabela.getColumnCount()]);
                      modelotabela.setValueAt(rs.getString("crm"), linha, 0);
                      modelotabela.setValueAt(rs.getString("nome"), linha, 1);
                      modelotabela.setValueAt(rs.getString("especialidade"), linha, 2);
                      linha++;
                  }
            }
        }catch(SQLException e){
            System.err.println("Erro: " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        edCRM = new javax.swing.JTextField();
        edNome = new javax.swing.JTextField();
        edEspecialidade = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        chSemFiltro = new javax.swing.JCheckBox();
        chNome = new javax.swing.JCheckBox();
        chEspecialidade = new javax.swing.JCheckBox();
        chCRM = new javax.swing.JCheckBox();
        btLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        lbErro = new javax.swing.JLabel();
        btInserir = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Busca de Médicos");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel5.setName(""); // NOI18N
        jPanel5.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Busca de Médicos");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(0, 20, 570, 30);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Filtros de busca:");
        jPanel6.add(jLabel6);
        jLabel6.setBounds(40, 10, 140, 20);

        edCRM.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edCRM.setEnabled(false);
        jPanel6.add(edCRM);
        edCRM.setBounds(120, 40, 100, 25);

        edNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edNome.setEnabled(false);
        jPanel6.add(edNome);
        edNome.setBounds(120, 70, 280, 25);

        edEspecialidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edEspecialidade.setEnabled(false);
        jPanel6.add(edEspecialidade);
        edEspecialidade.setBounds(120, 100, 280, 25);

        btBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btBuscar.setText("BUSCAR");
        btBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btBuscarMouseClicked(evt);
            }
        });
        jPanel6.add(btBuscar);
        btBuscar.setBounds(420, 80, 100, 50);

        buttonGroup1.add(chSemFiltro);
        chSemFiltro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chSemFiltro.setSelected(true);
        chSemFiltro.setText("Sem Filtro");
        jPanel6.add(chSemFiltro);
        chSemFiltro.setBounds(315, 40, 97, 30);

        buttonGroup1.add(chNome);
        chNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chNome.setText("Nome");
        chNome.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chNomeItemStateChanged(evt);
            }
        });
        jPanel6.add(chNome);
        chNome.setBounds(10, 70, 70, 24);

        buttonGroup1.add(chEspecialidade);
        chEspecialidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chEspecialidade.setText("Especialidade");
        chEspecialidade.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chEspecialidadeItemStateChanged(evt);
            }
        });
        jPanel6.add(chEspecialidade);
        chEspecialidade.setBounds(10, 100, 110, 24);

        buttonGroup1.add(chCRM);
        chCRM.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chCRM.setText("CRM");
        chCRM.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chCRMItemStateChanged(evt);
            }
        });
        jPanel6.add(chCRM);
        chCRM.setBounds(10, 40, 70, 24);

        btLimpar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.setToolTipText("");
        btLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btLimpar.setOpaque(false);
        btLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btLimparMouseClicked(evt);
            }
        });
        jPanel6.add(btLimpar);
        btLimpar.setBounds(420, 40, 100, 30);

        jPanel5.add(jPanel6);
        jPanel6.setBounds(20, 60, 530, 140);

        tabela.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 4"
            }
        ));
        tabela.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jScrollPane1.setViewportView(tabela);

        jPanel5.add(jScrollPane1);
        jScrollPane1.setBounds(20, 210, 530, 320);

        lbErro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbErro.setForeground(new java.awt.Color(255, 0, 51));
        lbErro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbErro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel5.add(lbErro);
        lbErro.setBounds(20, 540, 350, 30);

        btInserir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btInserir.setText("INSERIR");
        btInserir.setToolTipText("");
        btInserir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btInserirMouseClicked(evt);
            }
        });
        jPanel5.add(btInserir);
        btInserir.setBounds(20, 580, 110, 40);

        btVoltar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btVoltar.setText("VOLTAR");
        btVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btVoltarMouseClicked(evt);
            }
        });
        jPanel5.add(btVoltar);
        btVoltar.setBounds(450, 580, 100, 40);

        btRemover.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btRemover.setText("REMOVER");
        btRemover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btRemoverMouseClicked(evt);
            }
        });
        jPanel5.add(btRemover);
        btRemover.setBounds(260, 580, 110, 40);

        btAlterar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btAlterar.setText("ALTERAR");
        btAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAlterarMouseClicked(evt);
            }
        });
        jPanel5.add(btAlterar);
        btAlterar.setBounds(140, 580, 110, 40);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 0, 570, 630);

        setSize(new java.awt.Dimension(585, 669));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btBuscarMouseClicked
        search();
    }//GEN-LAST:event_btBuscarMouseClicked

    private void chNomeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chNomeItemStateChanged
        edNome.setEnabled(chNome.isSelected());
    }//GEN-LAST:event_chNomeItemStateChanged

    private void chEspecialidadeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chEspecialidadeItemStateChanged
        edEspecialidade.setEnabled(chEspecialidade.isSelected());
    }//GEN-LAST:event_chEspecialidadeItemStateChanged

    private void chCRMItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chCRMItemStateChanged
        edCRM.setEnabled(chCRM.isSelected());
    }//GEN-LAST:event_chCRMItemStateChanged
 
    private void btLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLimparMouseClicked
        edCRM.setText("");
        edNome.setText("");
        edEspecialidade.setText("");
        chSemFiltro.setSelected(true);
        btBuscarMouseClicked(evt);
    }//GEN-LAST:event_btLimparMouseClicked

    private void btInserirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btInserirMouseClicked
        InsereMedico insere = new InsereMedico();
        insere.setVisible(true);
    }//GEN-LAST:event_btInserirMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        search();
    }//GEN-LAST:event_formWindowActivated

    private void btVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVoltarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btVoltarMouseClicked

    private void btRemoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRemoverMouseClicked
        int crm;
        if(tabela.getSelectedRowCount() != 0){
            crm = Integer.parseInt(tabela.getValueAt(tabela.getSelectedRow(),0).toString());
            if((JOptionPane.showConfirmDialog(null, "Deseja realmente excluir?","Confirmação",JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE)) == JOptionPane.YES_OPTION){
                Medico m = new Medico(crm,"","");
                m.excluir();
                if (Medico.verificaExclusao(crm)){
                    lbErro.setText("");
                    JOptionPane.showMessageDialog(this, "Excluído com sucesso!", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
                    btBuscarMouseClicked(evt);
                } else {
                    lbErro.setText("Erro ao excluir!");
                } 
            }
        } else {
            lbErro.setText("Selecione uma linha para excluir!");
        }
    }//GEN-LAST:event_btRemoverMouseClicked

    private void btAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAlterarMouseClicked
         if(tabela.getSelectedRowCount() != 0){
            int crm = Integer.parseInt(tabela.getValueAt(tabela.getSelectedRow(),0).toString());
            ResultSet rs = Medico.consultar(""+crm,(short)1);
            try {
                lbErro.setText("");
                rs.next();
                Medico medico = new Medico(crm, rs.getString("nome"), rs.getString("especialidade"));
                InsereMedico alt = new InsereMedico(medico);
                alt.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(BuscaMedico.class.getName()).log(Level.SEVERE, null, ex);
            }   
        } else {
            lbErro.setText("Selecione uma linha para alterar");
        }
    }//GEN-LAST:event_btAlterarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscaMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new BuscaMedico().setVisible(true);
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btInserir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btRemover;
    private javax.swing.JButton btVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chCRM;
    private javax.swing.JCheckBox chEspecialidade;
    private javax.swing.JCheckBox chNome;
    private javax.swing.JCheckBox chSemFiltro;
    private javax.swing.JTextField edCRM;
    private javax.swing.JTextField edEspecialidade;
    private javax.swing.JTextField edNome;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbErro;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
