/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.unicamp.ic.mc536.prontosocorro;

import br.unicamp.ic.mc536.prontosocorro.consulta.BuscaConsulta;
import br.unicamp.ic.mc536.prontosocorro.doenca.BuscaDoenca;
import br.unicamp.ic.mc536.prontosocorro.laboratorio.BuscaLaboratorio;
import br.unicamp.ic.mc536.prontosocorro.medico.BuscaMedico;
import br.unicamp.ic.mc536.prontosocorro.paciente.BuscaPaciente;
import br.unicamp.ic.mc536.prontosocorro.medicamento.BuscaMedicamento;

/**
 *
 * @author aluno
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form telaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        mSistema = new javax.swing.JMenu();
        opFechar = new javax.swing.JMenuItem();
        mMedico = new javax.swing.JMenu();
        mPaciente = new javax.swing.JMenu();
        mConsulta = new javax.swing.JMenu();
        mExame = new javax.swing.JMenu();
        mMedicamento = new javax.swing.JMenu();
        mLaboratorio = new javax.swing.JMenu();
        mDoenca = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pronto, Socorro");
        setMinimumSize(new java.awt.Dimension(950, 700));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unicamp/ic/mc536/prontosocorro/cruz.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 110, 520, 360);

        menu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menu.setMargin(new java.awt.Insets(2, 2, 2, 2));
        menu.setName("menu"); // NOI18N
        menu.setPreferredSize(new java.awt.Dimension(950, 40));

        mSistema.setText("Sistema");
        mSistema.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mSistema.setMargin(new java.awt.Insets(5, 5, 5, 10));

        opFechar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        opFechar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        opFechar.setText("Fechar");
        opFechar.setMargin(new java.awt.Insets(5, 5, 5, 10));
        opFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opFecharActionPerformed(evt);
            }
        });
        mSistema.add(opFechar);

        menu.add(mSistema);

        mMedico.setText("Médico");
        mMedico.setAutoscrolls(true);
        mMedico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mMedico.setMargin(new java.awt.Insets(5, 5, 5, 10));
        mMedico.setName("mMedico"); // NOI18N
        mMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mMedicoMouseClicked(evt);
            }
        });
        menu.add(mMedico);

        mPaciente.setText("Paciente");
        mPaciente.setAutoscrolls(true);
        mPaciente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mPaciente.setMargin(new java.awt.Insets(5, 5, 5, 10));
        mPaciente.setName("mMedico"); // NOI18N
        mPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mPacienteMouseClicked(evt);
            }
        });
        menu.add(mPaciente);

        mConsulta.setText("Consulta");
        mConsulta.setAutoscrolls(true);
        mConsulta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mConsulta.setMargin(new java.awt.Insets(5, 5, 5, 10));
        mConsulta.setName("mMedico"); // NOI18N
        mConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mConsultaMouseClicked(evt);
            }
        });
        menu.add(mConsulta);

        mExame.setText("Exame");
        mExame.setAutoscrolls(true);
        mExame.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mExame.setMargin(new java.awt.Insets(5, 5, 5, 10));
        mExame.setName("mMedico"); // NOI18N
        menu.add(mExame);

        mMedicamento.setText("Medicamento");
        mMedicamento.setAutoscrolls(true);
        mMedicamento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mMedicamento.setMargin(new java.awt.Insets(5, 5, 5, 10));
        mMedicamento.setName("mMedico"); // NOI18N
        mMedicamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mMedicamentoMouseClicked(evt);
            }
        });
        menu.add(mMedicamento);

        mLaboratorio.setText("Laboratório");
        mLaboratorio.setAutoscrolls(true);
        mLaboratorio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mLaboratorio.setMargin(new java.awt.Insets(5, 5, 5, 10));
        mLaboratorio.setName("mMedico"); // NOI18N
        mLaboratorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mLaboratorioMouseClicked(evt);
            }
        });
        menu.add(mLaboratorio);

        mDoenca.setText("Doença");
        mDoenca.setAutoscrolls(true);
        mDoenca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mDoenca.setMargin(new java.awt.Insets(5, 5, 5, 10));
        mDoenca.setName("mMedico"); // NOI18N
        mDoenca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mDoencaMouseClicked(evt);
            }
        });
        menu.add(mDoenca);

        setJMenuBar(menu);

        setSize(new java.awt.Dimension(966, 739));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    private void opFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opFecharActionPerformed
        System.exit(0);
    }//GEN-LAST:event_opFecharActionPerformed

    private void mMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mMedicoMouseClicked
        BuscaMedico medico = new BuscaMedico();
        medico.setVisible(true);
    }//GEN-LAST:event_mMedicoMouseClicked

    private void mPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mPacienteMouseClicked
        BuscaPaciente paciente = new BuscaPaciente();
        paciente.setVisible(true);
    }//GEN-LAST:event_mPacienteMouseClicked


    private void mMedicamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mMedicamentoMouseClicked
         BuscaMedicamento medicamento = new BuscaMedicamento();
         medicamento.setVisible(true);
    }//GEN-LAST:event_mMedicamentoMouseClicked

    private void mDoencaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mDoencaMouseClicked
        BuscaDoenca doenca = new BuscaDoenca();
        doenca.setVisible(true);
    }//GEN-LAST:event_mDoencaMouseClicked

    private void mConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mConsultaMouseClicked
        BuscaConsulta consulta = new BuscaConsulta();
        consulta.setVisible(true);
    }//GEN-LAST:event_mConsultaMouseClicked

    private void mLaboratorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mLaboratorioMouseClicked
        BuscaLaboratorio laboratorio = new BuscaLaboratorio();
        laboratorio.setVisible(true);
    }//GEN-LAST:event_mLaboratorioMouseClicked


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu mConsulta;
    private javax.swing.JMenu mDoenca;
    private javax.swing.JMenu mExame;
    private javax.swing.JMenu mLaboratorio;
    private javax.swing.JMenu mMedicamento;
    private javax.swing.JMenu mMedico;
    private javax.swing.JMenu mPaciente;
    private javax.swing.JMenu mSistema;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem opFechar;
    // End of variables declaration//GEN-END:variables
}
