/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.unicamp.ic.mc536.prontosocorro;

import br.unicamp.ic.mc536.prontosocorro.doenca.BuscaDoenca;
import br.unicamp.ic.mc536.prontosocorro.laboratorio.BuscaLaboratorio;
import br.unicamp.ic.mc536.prontosocorro.medico.BuscaMedico;
import br.unicamp.ic.mc536.prontosocorro.paciente.BuscaPaciente;
import br.unicamp.ic.mc536.prontosocorro.medicamento.BuscaMedicamento;

/**
 *
 * @author aluno
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form telaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        mSistema = new javax.swing.JMenu();
        opFechar = new javax.swing.JMenuItem();
        mMedico = new javax.swing.JMenu();
        Paciente = new javax.swing.JMenu();
        mConsulta4 = new javax.swing.JMenu();
        mMedico5 = new javax.swing.JMenu();
        mMedico2 = new javax.swing.JMenu();
        mMedico6 = new javax.swing.JMenu();
        Doenca = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pronto, Socorro");
        setMinimumSize(new java.awt.Dimension(950, 700));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unicamp/ic/mc536/prontosocorro/cruz.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 110, 520, 360);

        menu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menu.setMargin(new java.awt.Insets(2, 2, 2, 2));
        menu.setName("menu"); // NOI18N
        menu.setPreferredSize(new java.awt.Dimension(950, 40));

        mSistema.setText("Sistema");
        mSistema.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mSistema.setMargin(new java.awt.Insets(5, 5, 5, 10));

        opFechar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        opFechar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        opFechar.setText("Fechar");
        opFechar.setMargin(new java.awt.Insets(5, 5, 5, 10));
        opFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opFecharActionPerformed(evt);
            }
        });
        mSistema.add(opFechar);

        menu.add(mSistema);

        mMedico.setText("Médico");
        mMedico.setAutoscrolls(true);
        mMedico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mMedico.setMargin(new java.awt.Insets(5, 5, 5, 10));
        mMedico.setName("mMedico"); // NOI18N
        mMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mMedicoMouseClicked(evt);
            }
        });
        menu.add(mMedico);

        Paciente.setText("Paciente");
        Paciente.setAutoscrolls(true);
        Paciente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Paciente.setMargin(new java.awt.Insets(5, 5, 5, 10));
        Paciente.setName("mMedico"); // NOI18N
        Paciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PacienteMouseClicked(evt);
            }
        });
        menu.add(Paciente);

        mConsulta4.setText("Consulta");
        mConsulta4.setAutoscrolls(true);
        mConsulta4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mConsulta4.setMargin(new java.awt.Insets(5, 5, 5, 10));
        mConsulta4.setName("mMedico"); // NOI18N
        menu.add(mConsulta4);

        mMedico5.setText("Exame");
        mMedico5.setAutoscrolls(true);
        mMedico5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mMedico5.setMargin(new java.awt.Insets(5, 5, 5, 10));
        mMedico5.setName("mMedico"); // NOI18N
        menu.add(mMedico5);

        mMedico2.setText("Medicamento");
        mMedico2.setAutoscrolls(true);
        mMedico2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mMedico2.setMargin(new java.awt.Insets(5, 5, 5, 10));
        mMedico2.setName("mMedico"); // NOI18N
        mMedico2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mMedico2MouseClicked(evt);
            }
        });
        menu.add(mMedico2);

        mMedico6.setText("Laboratório");
        mMedico6.setAutoscrolls(true);
        mMedico6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mMedico6.setMargin(new java.awt.Insets(5, 5, 5, 10));
        mMedico6.setName("mMedico"); // NOI18N
        mMedico6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mMedico6MouseClicked(evt);
            }
        });
        menu.add(mMedico6);

        Doenca.setText("Doença");
        Doenca.setAutoscrolls(true);
        Doenca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Doenca.setMargin(new java.awt.Insets(5, 5, 5, 10));
        Doenca.setName("mMedico"); // NOI18N
        Doenca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DoencaMouseClicked(evt);
            }
        });
        menu.add(Doenca);

        setJMenuBar(menu);

        setSize(new java.awt.Dimension(966, 739));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    private void opFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opFecharActionPerformed
        System.exit(0);
    }//GEN-LAST:event_opFecharActionPerformed

    private void mMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mMedicoMouseClicked
        BuscaMedico medico = new BuscaMedico();
        medico.setVisible(true);
    }//GEN-LAST:event_mMedicoMouseClicked

    private void PacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PacienteMouseClicked
        BuscaPaciente paciente = new BuscaPaciente();
        paciente.setVisible(true);
    }//GEN-LAST:event_PacienteMouseClicked


    private void mMedico2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mMedico2MouseClicked
         BuscaMedicamento medicamento = new BuscaMedicamento();
         medicamento.setVisible(true);
    }//GEN-LAST:event_mMedico2MouseClicked

    private void DoencaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoencaMouseClicked
        BuscaDoenca doenca = new BuscaDoenca();
        doenca.setVisible(true);
    }//GEN-LAST:event_DoencaMouseClicked

    private void mMedico6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mMedico6MouseClicked
        BuscaLaboratorio laboratorio = new BuscaLaboratorio();
        laboratorio.setVisible(true);
    }//GEN-LAST:event_mMedico6MouseClicked


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Doenca;
    private javax.swing.JMenu Paciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu mConsulta4;
    private javax.swing.JMenu mMedico;
    private javax.swing.JMenu mMedico2;
    private javax.swing.JMenu mMedico5;
    private javax.swing.JMenu mMedico6;
    private javax.swing.JMenu mSistema;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem opFechar;
    // End of variables declaration//GEN-END:variables
}
