/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.unicamp.ic.mc536.prontosocorro.tratamento;
import br.unicamp.ic.mc536.prontosocorro.medico.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Administrador
 */
public class BuscaTratamento extends javax.swing.JFrame {

    /**
     * Creates new form ConsFuncionario
     */
    public BuscaTratamento() {
        initComponents();
    }
    
    private void search() {
        if (chSemFiltro.isSelected()){
            atualizaTabela(Tratamento.consultar());
            lbErro.setText("");
        } else if(chMedicamento.isSelected()) {   
            try {
                int m = Integer.parseInt(edMedicamento.getText());
                atualizaTabela(Tratamento.consultar(""+m,(short)1));
                lbErro.setText(""); 
            } catch (NumberFormatException e) {
                lbErro.setText("Medicamento inválido"); 
            }            
        } else if(chPrincipioAtivo.isSelected()) {            
            atualizaTabela(Tratamento.consultar(edPrincipioAtivo.getText().trim(),(short)2));
            lbErro.setText("");            
        } else if(chCID.isSelected()) {
            atualizaTabela(Tratamento.consultar(edCID.getText().trim(),(short)3));
            lbErro.setText("");
        }
    }
    
    protected void atualizaTabela(ResultSet rs){
        DefaultTableModel modelotabela = (DefaultTableModel) tabela.getModel();
        modelotabela.setColumnCount(3);
        modelotabela.setRowCount(0);

        tabela.getColumnModel().getColumn(0).setHeaderValue("ID Medicamento");
        tabela.getColumnModel().getColumn(1).setHeaderValue("Princípio Ativo");
        tabela.getColumnModel().getColumn(2).setHeaderValue("CID");
        int linha = 0;
        try{
            if(rs != null) {  
                while(rs.next()){
                      modelotabela.addRow(new String[modelotabela.getColumnCount()]);
                      modelotabela.setValueAt(rs.getInt("medicamento"), linha, 0);
                      modelotabela.setValueAt(rs.getString("principio_ativo"), linha, 1);
                      modelotabela.setValueAt(rs.getString("doenca"), linha, 2);
                      linha++;
                  }
            }
        }catch(SQLException e){
            System.err.println("Erro: " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        edPrincipioAtivo = new javax.swing.JTextField();
        edCID = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        chSemFiltro = new javax.swing.JCheckBox();
        chCID = new javax.swing.JCheckBox();
        chPrincipioAtivo = new javax.swing.JCheckBox();
        btLimpar = new javax.swing.JButton();
        edMedicamento = new javax.swing.JTextField();
        chMedicamento = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        lbErro = new javax.swing.JLabel();
        btInserir = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Busca de Médicos");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel5.setName(""); // NOI18N
        jPanel5.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Busca de Tratamentos");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(0, 20, 700, 30);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Filtros de busca:");
        jPanel6.add(jLabel6);
        jLabel6.setBounds(40, 10, 140, 20);

        edPrincipioAtivo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edPrincipioAtivo.setEnabled(false);
        jPanel6.add(edPrincipioAtivo);
        edPrincipioAtivo.setBounds(160, 110, 310, 25);

        edCID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edCID.setEnabled(false);
        jPanel6.add(edCID);
        edCID.setBounds(160, 50, 100, 25);

        btBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btBuscar.setText("BUSCAR");
        btBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btBuscarMouseClicked(evt);
            }
        });
        jPanel6.add(btBuscar);
        btBuscar.setBounds(550, 70, 100, 50);

        buttonGroup1.add(chSemFiltro);
        chSemFiltro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chSemFiltro.setSelected(true);
        chSemFiltro.setText("Sem Filtro");
        jPanel6.add(chSemFiltro);
        chSemFiltro.setBounds(370, 40, 97, 30);

        buttonGroup1.add(chCID);
        chCID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chCID.setText("CID");
        chCID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chCIDItemStateChanged(evt);
            }
        });
        jPanel6.add(chCID);
        chCID.setBounds(10, 50, 70, 24);

        buttonGroup1.add(chPrincipioAtivo);
        chPrincipioAtivo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chPrincipioAtivo.setText("Princípio Ativo");
        chPrincipioAtivo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chPrincipioAtivoItemStateChanged(evt);
            }
        });
        jPanel6.add(chPrincipioAtivo);
        chPrincipioAtivo.setBounds(10, 110, 130, 24);
        chPrincipioAtivo.getAccessibleContext().setAccessibleName("Princípio Ativo");

        btLimpar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.setToolTipText("");
        btLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btLimparMouseClicked(evt);
            }
        });
        jPanel6.add(btLimpar);
        btLimpar.setBounds(550, 30, 100, 30);

        edMedicamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edMedicamento.setEnabled(false);
        jPanel6.add(edMedicamento);
        edMedicamento.setBounds(160, 80, 100, 25);

        buttonGroup1.add(chMedicamento);
        chMedicamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chMedicamento.setText("ID Medicamento");
        chMedicamento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chMedicamentoItemStateChanged(evt);
            }
        });
        jPanel6.add(chMedicamento);
        chMedicamento.setBounds(10, 80, 140, 24);

        jPanel5.add(jPanel6);
        jPanel6.setBounds(20, 60, 660, 150);

        tabela.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 4"
            }
        ));
        tabela.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jScrollPane1.setViewportView(tabela);

        jPanel5.add(jScrollPane1);
        jScrollPane1.setBounds(20, 220, 660, 320);

        lbErro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbErro.setForeground(new java.awt.Color(255, 0, 51));
        lbErro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbErro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel5.add(lbErro);
        lbErro.setBounds(20, 550, 350, 30);

        btInserir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btInserir.setText("INSERIR");
        btInserir.setToolTipText("");
        btInserir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btInserirMouseClicked(evt);
            }
        });
        jPanel5.add(btInserir);
        btInserir.setBounds(20, 590, 110, 40);

        btVoltar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btVoltar.setText("VOLTAR");
        btVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btVoltarMouseClicked(evt);
            }
        });
        jPanel5.add(btVoltar);
        btVoltar.setBounds(580, 590, 100, 40);

        btRemover.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btRemover.setText("REMOVER");
        btRemover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btRemoverMouseClicked(evt);
            }
        });
        jPanel5.add(btRemover);
        btRemover.setBounds(260, 590, 110, 40);

        btAlterar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btAlterar.setText("ALTERAR");
        btAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAlterarMouseClicked(evt);
            }
        });
        jPanel5.add(btAlterar);
        btAlterar.setBounds(140, 590, 110, 40);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 0, 710, 640);

        setSize(new java.awt.Dimension(716, 678));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btBuscarMouseClicked
        search();
    }//GEN-LAST:event_btBuscarMouseClicked

    private void chCIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chCIDItemStateChanged
        edCID.setEnabled(chCID.isSelected());
    }//GEN-LAST:event_chCIDItemStateChanged

    private void chPrincipioAtivoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chPrincipioAtivoItemStateChanged
        edPrincipioAtivo.setEnabled(chPrincipioAtivo.isSelected());
    }//GEN-LAST:event_chPrincipioAtivoItemStateChanged
 
    private void btLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLimparMouseClicked
        edPrincipioAtivo.setText("");
        edCID.setText("");
        chSemFiltro.setSelected(true);
        btBuscarMouseClicked(evt);
    }//GEN-LAST:event_btLimparMouseClicked

    private void btInserirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btInserirMouseClicked
        InsereTratamento insere = new InsereTratamento();
        insere.setVisible(true);
    }//GEN-LAST:event_btInserirMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        search();
    }//GEN-LAST:event_formWindowActivated

    private void btVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVoltarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btVoltarMouseClicked

    private void btRemoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRemoverMouseClicked
        
        if(tabela.getSelectedRowCount() != 0){
            int medic = Integer.parseInt(tabela.getValueAt(tabela.getSelectedRow(),0).toString());
            String doenca = tabela.getValueAt(tabela.getSelectedRow(),2).toString();
            if((JOptionPane.showConfirmDialog(null, "Deseja realmente excluir?","Confirmação",JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE)) == JOptionPane.YES_OPTION){
                
                Tratamento t = new Tratamento(medic, "", doenca, "");
                t.excluir();
                
                lbErro.setText("");
                JOptionPane.showMessageDialog(this, "Excluído com sucesso!", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
               
            }
        } else {
            lbErro.setText("Selecione uma linha para excluir!");
        }
    }//GEN-LAST:event_btRemoverMouseClicked

    private void btAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAlterarMouseClicked
         if(tabela.getSelectedRowCount() != 0){
            int medic = Integer.parseInt(tabela.getValueAt(tabela.getSelectedRow(),0).toString());
            String doenca = tabela.getValueAt(tabela.getSelectedRow(),2).toString();
            ResultSet rs = Tratamento.consultar(medic+"",doenca);
            try {
                lbErro.setText("");
                rs.next();
                Tratamento tratamento = new Tratamento(medic, "", doenca, rs.getString("descricao"));
                InsereTratamento alt = new InsereTratamento(tratamento);
                alt.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(BuscaTratamento.class.getName()).log(Level.SEVERE, null, ex);
            }   
        } else {
            lbErro.setText("Selecione uma linha para alterar");
        }
    }//GEN-LAST:event_btAlterarMouseClicked

    private void chMedicamentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chMedicamentoItemStateChanged
        edMedicamento.setEnabled(chMedicamento.isSelected());
    }//GEN-LAST:event_chMedicamentoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscaTratamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new BuscaTratamento().setVisible(true);
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btInserir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btRemover;
    private javax.swing.JButton btVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chCID;
    private javax.swing.JCheckBox chMedicamento;
    private javax.swing.JCheckBox chPrincipioAtivo;
    private javax.swing.JCheckBox chSemFiltro;
    private javax.swing.JTextField edCID;
    private javax.swing.JTextField edMedicamento;
    private javax.swing.JTextField edPrincipioAtivo;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbErro;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
