package br.unicamp.ic.mc536.prontosocorro.tratamento;

import br.unicamp.ic.mc536.prontosocorro.medico.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aluno
 */
public class InsereTratamento extends javax.swing.JFrame {

    /**
     * Creates new form CadastroClienteFisica
     */
    
    boolean flagUpdate;
    Tratamento tratamento;
    
    public InsereTratamento() {
        initComponents();
        flagUpdate = false;
    }
    
    public InsereTratamento(Tratamento t) {
        initComponents();
        tratamento = t;
        flagUpdate = true;
        inicializaCampos();
        edMedicamento.setEditable(false);
        edDoenca.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        edDoenca = new javax.swing.JTextField();
        edMedicamento = new javax.swing.JTextField();
        btConfirma = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        lbErro = new javax.swing.JLabel();
        JScrollPane1 = new javax.swing.JScrollPane();
        taDescricao = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Médicos");
        setName("janela"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cadastro de Tratamentos:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 20, 550, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("* Doença");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 110, 100, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("* Medicamento");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 80, 110, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Descrição");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 140, 100, 20);

        edDoenca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(edDoenca);
        edDoenca.setBounds(130, 110, 260, 25);

        edMedicamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(edMedicamento);
        edMedicamento.setBounds(130, 80, 140, 25);

        btConfirma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btConfirma.setText("CONFIRMA");
        btConfirma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btConfirmaMouseClicked(evt);
            }
        });
        jPanel1.add(btConfirma);
        btConfirma.setBounds(150, 290, 120, 40);

        btVoltar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btVoltar.setText("VOLTAR");
        btVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btVoltarMouseClicked(evt);
            }
        });
        jPanel1.add(btVoltar);
        btVoltar.setBounds(280, 290, 120, 40);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("* Campo Obrigatório");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(390, 260, 150, 17);

        lbErro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbErro.setForeground(new java.awt.Color(255, 0, 51));
        lbErro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbErro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbErro);
        lbErro.setBounds(10, 250, 360, 30);

        taDescricao.setColumns(20);
        taDescricao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        taDescricao.setLineWrap(true);
        taDescricao.setRows(5);
        JScrollPane1.setViewportView(taDescricao);

        jPanel1.add(JScrollPane1);
        JScrollPane1.setBounds(130, 140, 400, 100);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -2, 570, 360);

        setSize(new java.awt.Dimension(566, 380));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btConfirmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btConfirmaMouseClicked
        try {
            String doenca = edDoenca.getText().trim().toUpperCase();
            int medicamento = Integer.parseInt(edMedicamento.getText().trim());
            
            if((doenca.equals("")) || (medicamento == 0)){            
                lbErro.setText("Preencha os campos obrigatórios");
            } else {  
                Tratamento trat = new Tratamento(medicamento, "", doenca,taDescricao.getText());
                if (!flagUpdate) {
                    trat.novo();
                    JOptionPane.showMessageDialog(this, "Cadastrado com sucesso!", "Cadastro", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    trat.alterar();
                    JOptionPane.showMessageDialog(this, "Alterado com sucesso!", "Atualização", JOptionPane.INFORMATION_MESSAGE);
                }
                
                this.dispose();
            }
        } catch (NumberFormatException e) {
            lbErro.setText("Medicamento inválido");        
        }
        
    }//GEN-LAST:event_btConfirmaMouseClicked

    private void btVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVoltarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btVoltarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsereTratamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new InsereTratamento().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPane1;
    private javax.swing.JButton btConfirma;
    private javax.swing.JButton btVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField edDoenca;
    private javax.swing.JTextField edMedicamento;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbErro;
    private javax.swing.JTextArea taDescricao;
    // End of variables declaration//GEN-END:variables
    
    private void inicializaCampos() {
        edMedicamento.setText(""+tratamento.getMedicamento());
        edDoenca.setText(tratamento.getDoenca());
        taDescricao.setText(tratamento.getDescricao());
    }
}
