/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.unicamp.ic.mc536.prontosocorro.laboratorio;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Administrador
 */
public class BuscaLaboratorio extends javax.swing.JFrame {

    /**
     * Creates new form ConsFuncionario
     */
    public BuscaLaboratorio() {
        initComponents();
    }
    
    private void search() {
        if (chSemFiltro.isSelected()){
            atualizaTabela(Laboratorio.consultar("",(short)-1));
            lbErro.setText("");
        } else if(chRegistro.isSelected()) {
            try {
                String nRegistro = edRegistro.getText();
                atualizaTabela(Laboratorio.consultar(edRegistro.getText(),(short)1));
                lbErro.setText("");
            } catch (NumberFormatException e) {
                lbErro.setText("O código deve ser um valor numérico!");
            }
        } else if(chNome.isSelected()) {
            atualizaTabela(Laboratorio.consultar(edNome.getText(),(short)2));
            lbErro.setText("");
        } else if(chTipo.isSelected()) {
            atualizaTabela(Laboratorio.consultar(edTipo.getText(),(short)3));
            lbErro.setText("");
        } 
    }
    
    protected void atualizaTabela(ResultSet rs){
        DefaultTableModel modelotabela = (DefaultTableModel) tabela.getModel();
        modelotabela.setColumnCount(5);
        modelotabela.setRowCount(0);

        tabela.getColumnModel().getColumn(0).setHeaderValue("Registro");
        tabela.getColumnModel().getColumn(1).setHeaderValue("Nome");
        tabela.getColumnModel().getColumn(2).setHeaderValue("Telefone");
        tabela.getColumnModel().getColumn(3).setHeaderValue("Tipo");
        tabela.getColumnModel().getColumn(4).setHeaderValue("Responsável");
        
        int linha = 0;
        try{
            if(rs != null) {  
                while(rs.next()){
                      modelotabela.addRow(new String[modelotabela.getColumnCount()]);
                      modelotabela.setValueAt(rs.getString("nRegistro"), linha, 0);
                      modelotabela.setValueAt(rs.getString("nome"), linha, 1);
                      modelotabela.setValueAt(rs.getString("telefone"), linha, 2);
                      modelotabela.setValueAt(rs.getString("tipo"), linha, 3);
                      modelotabela.setValueAt(rs.getString("responsavel"), linha, 4);
                      linha++;
                  }
            }
        }catch(SQLException e){
            System.err.println("Erro: " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        edTipo = new javax.swing.JTextField();
        edNome = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        chSemFiltro = new javax.swing.JCheckBox();
        chNome = new javax.swing.JCheckBox();
        chTipo = new javax.swing.JCheckBox();
        btLimpar = new javax.swing.JButton();
        chRegistro = new javax.swing.JCheckBox();
        edRegistro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        lbErro = new javax.swing.JLabel();
        btInserir = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Busca de Paciente");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel5.setName(""); // NOI18N
        jPanel5.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Busca de Laboratório");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(0, 20, 570, 30);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Filtros de busca:");
        jPanel6.add(jLabel6);
        jLabel6.setBounds(40, 10, 140, 20);

        edTipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edTipo.setEnabled(false);
        jPanel6.add(edTipo);
        edTipo.setBounds(120, 70, 130, 27);

        edNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edNome.setEnabled(false);
        jPanel6.add(edNome);
        edNome.setBounds(120, 100, 280, 27);

        btBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btBuscar.setText("BUSCAR");
        btBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btBuscarMouseClicked(evt);
            }
        });
        jPanel6.add(btBuscar);
        btBuscar.setBounds(420, 80, 100, 50);

        buttonGroup1.add(chSemFiltro);
        chSemFiltro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chSemFiltro.setSelected(true);
        chSemFiltro.setText("Sem Filtro");
        jPanel6.add(chSemFiltro);
        chSemFiltro.setBounds(315, 40, 103, 30);

        buttonGroup1.add(chNome);
        chNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chNome.setText("Nome");
        chNome.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chNomeItemStateChanged(evt);
            }
        });
        jPanel6.add(chNome);
        chNome.setBounds(10, 100, 70, 23);

        buttonGroup1.add(chTipo);
        chTipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chTipo.setText("Tipo");
        chTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chTipoItemStateChanged(evt);
            }
        });
        chTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chTipoActionPerformed(evt);
            }
        });
        jPanel6.add(chTipo);
        chTipo.setBounds(10, 70, 70, 23);

        btLimpar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.setToolTipText("");
        btLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btLimparMouseClicked(evt);
            }
        });
        jPanel6.add(btLimpar);
        btLimpar.setBounds(420, 40, 100, 30);

        buttonGroup1.add(chRegistro);
        chRegistro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chRegistro.setText("Registro");
        chRegistro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chRegistroItemStateChanged(evt);
            }
        });
        chRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chRegistroActionPerformed(evt);
            }
        });
        jPanel6.add(chRegistro);
        chRegistro.setBounds(10, 40, 90, 23);

        edRegistro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edRegistro.setEnabled(false);
        jPanel6.add(edRegistro);
        edRegistro.setBounds(120, 40, 100, 27);

        jPanel5.add(jPanel6);
        jPanel6.setBounds(20, 60, 530, 140);

        tabela.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 4", "Título 2"
            }
        ));
        tabela.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jScrollPane1.setViewportView(tabela);

        jPanel5.add(jScrollPane1);
        jScrollPane1.setBounds(20, 210, 530, 320);

        lbErro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbErro.setForeground(new java.awt.Color(255, 0, 51));
        lbErro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbErro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel5.add(lbErro);
        lbErro.setBounds(20, 540, 350, 30);

        btInserir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btInserir.setText("INSERIR");
        btInserir.setToolTipText("");
        btInserir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btInserirMouseClicked(evt);
            }
        });
        btInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirActionPerformed(evt);
            }
        });
        jPanel5.add(btInserir);
        btInserir.setBounds(20, 580, 110, 40);

        btVoltar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btVoltar.setText("VOLTAR");
        btVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btVoltarMouseClicked(evt);
            }
        });
        jPanel5.add(btVoltar);
        btVoltar.setBounds(450, 580, 100, 40);

        btRemover.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btRemover.setText("REMOVER");
        btRemover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btRemoverMouseClicked(evt);
            }
        });
        jPanel5.add(btRemover);
        btRemover.setBounds(260, 580, 110, 40);

        btAlterar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btAlterar.setText("ALTERAR");
        btAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAlterarMouseClicked(evt);
            }
        });
        jPanel5.add(btAlterar);
        btAlterar.setBounds(140, 580, 110, 40);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 0, 570, 630);

        setSize(new java.awt.Dimension(584, 669));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btBuscarMouseClicked
        search();
    }//GEN-LAST:event_btBuscarMouseClicked

    private void chNomeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chNomeItemStateChanged
        edNome.setEnabled(chNome.isSelected());
    }//GEN-LAST:event_chNomeItemStateChanged

    private void chTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chTipoItemStateChanged
        edTipo.setEnabled(chTipo.isSelected());
    }//GEN-LAST:event_chTipoItemStateChanged
 
    private void btLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLimparMouseClicked
        edTipo.setText("");
        edNome.setText("");
        edRegistro.setText("");
        chSemFiltro.setSelected(true);
        btBuscarMouseClicked(evt);
    }//GEN-LAST:event_btLimparMouseClicked

    private void btInserirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btInserirMouseClicked
        InsereLaboratorio insere = new InsereLaboratorio();
        insere.setVisible(true);
    }//GEN-LAST:event_btInserirMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        search();
    }//GEN-LAST:event_formWindowActivated

    private void btVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVoltarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btVoltarMouseClicked

    private void btRemoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRemoverMouseClicked
        int nRegistro;
        if(tabela.getSelectedRowCount() != 0){
            nRegistro = Integer.parseInt(tabela.getValueAt(tabela.getSelectedRow(),0).toString());
            if((JOptionPane.showConfirmDialog(null, "Deseja realmente excluir?","Confirmação",JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE)) == JOptionPane.YES_OPTION){
                Laboratorio l = new Laboratorio(nRegistro,"","","","");
                l.excluir();
                if (Laboratorio.verificaExclusao(nRegistro)){
                    lbErro.setText("");
                    JOptionPane.showMessageDialog(this, "Excluído com sucesso!", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
                    btBuscarMouseClicked(evt);
                } else {
                    lbErro.setText("Erro ao excluir!");
                } 
            }
        } else {
            lbErro.setText("Selecione uma linha para excluir!");
        }
    }//GEN-LAST:event_btRemoverMouseClicked

    private void btAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAlterarMouseClicked
         if(tabela.getSelectedRowCount() != 0){
            int nRegistro = Integer.parseInt(tabela.getValueAt(tabela.getSelectedRow(),0).toString());
            ResultSet rs = Laboratorio.consultar(""+nRegistro,(short)1);
            try {
                lbErro.setText("");
                rs.next();
                Laboratorio laboratorio = new Laboratorio(nRegistro, rs.getString("nome"), rs.getString("telefone"),rs.getString("tipo"),rs.getString("responsavel"));
                InsereLaboratorio alt = new InsereLaboratorio(laboratorio);
                alt.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(BuscaLaboratorio.class.getName()).log(Level.SEVERE, null, ex);
            }   
        } else {
            lbErro.setText("Selecione uma linha para alterar");
        }
    }//GEN-LAST:event_btAlterarMouseClicked

    private void btInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btInserirActionPerformed

    private void chTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chTipoActionPerformed

    private void chRegistroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chRegistroItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_chRegistroItemStateChanged

    private void chRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscaLaboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new BuscaLaboratorio().setVisible(true);
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btInserir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btRemover;
    private javax.swing.JButton btVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chNome;
    private javax.swing.JCheckBox chRegistro;
    private javax.swing.JCheckBox chSemFiltro;
    private javax.swing.JCheckBox chTipo;
    private javax.swing.JTextField edNome;
    private javax.swing.JTextField edRegistro;
    private javax.swing.JTextField edTipo;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbErro;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
